# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: davies k kaimenyi
email: kika.dave@gmail.com
description1: Research fellow

baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: kika_dave
github_username:  davekk

# Build settings
markdown: kramdown

# For SEO optimization
plugins:
  - jekyll-seo-tag

# Enable linking to header anchors
kramdown:
  auto_ids: true

theme: jekyll-theme-architect